AWSTemplateFormatVersion: '2010-09-09'
Description: >
  S3 bucket + CloudFront distribution with Origin Access Identity (OAI).
  Bucket is private; CloudFront is allowed to read objects via OAI.

Parameters:
  BucketName:
    Type: String
    Default: ""
    Description: Optional. Provide a name to create a bucket with that name. Leave blank for a generated name.
  PriceClass:
    Type: String
    Default: PriceClass_100
    AllowedValues: [PriceClass_100, PriceClass_200, PriceClass_All]
    Description: CloudFront price class
  EnableVersioning:
    Type: String
    AllowedValues: [true, false]
    Default: false
    Description: Enable S3 versioning (true/false)

Conditions:
  HasBucketName: !Not [ !Equals [ !Ref BucketName, "" ] ]
  VersioningEnabled: !Equals [ !Ref EnableVersioning, "true" ]

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [ HasBucketName, !Ref BucketName, !Ref AWS::NoValue ]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: !If
        - VersioningEnabled
        - Status: Enabled
        - !Ref AWS::NoValue

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "${WebsiteBucket.Arn}/*"

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        Comment: !Sub "CF distribution for ${AWS::StackName}"

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref WebsiteBucket
  DistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
  CloudFrontOAIId:
    Description: Origin Access Identity ID
    Value: !Ref CloudFrontOAI
