AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Secure S3 bucket with versioning, SSE-S3, lifecycle for non-current versions,
  public access blocking, and a TLS-enforcing bucket policy. Optional BucketName parameter.

Parameters:
  BucketName:
    Type: String
    Default: ""
    Description: "Optional: specify a bucket name. Leave empty to let CloudFormation generate one."

Conditions:
  UseProvidedName: !Not [ !Equals [ !Ref BucketName, "" ] ]

Resources:
  SecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [ UseProvidedName, !Ref BucketName, !Ref "AWS::NoValue" ]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionTransition
            Status: Enabled
            NoncurrentVersionTransitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
            NoncurrentVersionExpiration:
              NoncurrentDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EnforceTLSBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnencryptedTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${SecureS3Bucket}"
              - !Sub "arn:aws:s3:::${SecureS3Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: "Created bucket name"
    Value: !Ref SecureS3Bucket

  BucketArn:
    Description: "Bucket ARN"
    Value: !Sub "arn:aws:s3:::${SecureS3Bucket}"
