AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Secure S3 bucket with server-side encryption, versioning, lifecycle rules
  and a bucket policy that denies non-TLS or unencrypted uploads.

Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjects365
            Status: Enabled
            ExpirationInDays: 365
          - Id: TransitionToIA30
            Status: Enabled
            Transition:
              StorageClass: STANDARD_IA
              TransitionInDays: 30
          - Id: ExpireNoncurrentVersions30
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${SecureBucket}/*"
            Condition:
              Null:
                "s3:x-amz-server-side-encryption": true
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${SecureBucket}"
              - !Sub "arn:aws:s3:::${SecureBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

Outputs:
  BucketName:
    Description: "Secure bucket name"
    Value: !Ref SecureBucket
  BucketArn:
    Description: "Secure bucket ARN"
    Value: !Sub "arn:aws:s3:::${SecureBucket}"
