AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Secure S3 bucket with versioning, SSE-S3 encryption, lifecycle rules,
  and public access blocking.

Parameters:
  BucketName:
    Type: String
    Default: ''
    Description: Optional bucket name. Leave empty to let CloudFormation generate a name.
  IATransitionDays:
    Type: Number
    Default: 30
    Description: Days before objects transition to STANDARD_IA.

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: !Ref IATransitionDays
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            NoncurrentVersionExpiration:
              NoncurrentDays: 365
          - Id: AbortIncompleteMultipart
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  S3PublicAccessBlock:
    Type: AWS::S3::BucketPublicAccessBlock
    Properties:
      Bucket: !Ref S3Bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  BucketArn:
    Description: ARN of the created bucket
    Value: !GetAtt S3Bucket.Arn
