AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Secure S3 bucket with SSE-S3, versioning, lifecycle rules, and public access block.

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment tag (e.g., dev, staging, prod)

  TransitionToIAInDays:
    Type: Number
    Default: 30
    Description: Days before objects transition to STANDARD_IA

  TransitionToGlacierInDays:
    Type: Number
    Default: 365
    Description: Days before objects transition to GLACIER

Resources:
  SecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: !Ref TransitionToIAInDays
          - Id: TransitionToGlacier
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: !Ref TransitionToGlacierInDays
          - Id: AbortIncompleteMultipartUpload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  EnforceHttpsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${SecureS3Bucket.Arn}"
              - !Sub "${SecureS3Bucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref SecureS3Bucket
  BucketArn:
    Description: The ARN of the created S3 bucket
    Value: !GetAtt SecureS3Bucket.Arn
